version: '3.11.2'

services:
  web:
    build: .
    command: python /dk_django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dk_django
    ports:
      - 8000:8000
    links:
      - db:db
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
